### ISSUE TITLE
use Tuple for partition results

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-arrays#102]
The result structure for `partition` is a bit idiosyncratic:

```purescript
partition :: forall a. (a -> Boolean) -> Array a -> { yes :: Array a, no :: Array a }
```

I get the impression that, over time, purescript APIs have been preferring `Tuple`s for this kind of thing, rather than ad-hoc records. What do people think of either (breaking) switching the API to returning a Tuple, or making a `partition'` that returns `Tuple`s?

For comparison, `partition` from the Haskell prelude:

```haskell
partition :: (a -> Bool) -> [a] -> ([a], [a])
```

**Comment by hdgarrood** [comment]
Personally I prefer it how it is, see my comment in https://github.com/purescript/purescript-lists/issues/117
