### ISSUE TITLE
Provide a function that takes an ST computation that returns an STArray, and returns an Array, without any copying

### ISSUE THREAD

**Issue by rightfold** [purescript/purescript-arrays#104]
This is perfectly safe, due to state thread scopes, yet currently the docs suggest that people use `unsafeFreeze` manually.

**Comment by hdgarrood** [comment]
The current `runSTArray` is deprecated because the open effect row means that you can do things like saving the mutable reference in a `Ref`, which makes it unsafe. I wouldn't mind un-deprecating it if we changed its signature at the same time to use a closed row, like this:

```purescript
runSTArray :: forall a h. (forall h. Eff (st :: ST h) (STArray a)) -> Array a
```

See #87 and #89 for how we ended up at the current design.

**Comment by hdgarrood** [comment]
Although in that case a better name might be `pureSTArray`, like with `pureST`.

**Comment by rightfold** [comment]
If you unsafeFreeze an STArray from a pureST, you can still mutate it from a deferred Aff action, because launchAff introduces no effects other than EXCEPTION, which can be removed

**Comment by hdgarrood** [comment]
I wonder if that's really a problem with Aff's API...

**Comment by natefaubion** [comment]
> I wonder if that's really a problem with Aff's API...

It is. Scheduling is an effect. So either `runAff` needs to introduce an `ASYNC` effect, or `delay` should introduce an effect. All other scheduler type things (like `setTimeout`) have their own effect.

**Comment by hdgarrood** [comment]
I'm actually beginning to wonder, in discussions like these, whether it would make sense to make the fact that `ST` is based on `Eff` an implementation detail; to use a newtype over `Eff` so that `Eff` doesn't appear in any of the type signatures exported by this library.

**Comment by natefaubion** [comment]
https://github.com/purescript/purescript-st/issues/8
