### ISSUE TITLE
Add dropRight and takeRight?

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-arrays#113]
What you think to add similar functions?
do you like this names? 
https://lodash.com/docs/4.17.4#dropRight
https://lodash.com/docs/4.17.4#takeRight

```
dropRight n arr = take (length arr - n) arr
takeRight n arr = drop (length arr - n) arr
```

**Comment by safareli** [comment]
let's use `*End` as names 
http://hackage.haskell.org/package/text-1.2.2.1/docs/Data-Text.html#v:dropEnd
https://hackage.haskell.org/package/extra-1.6/docs/Data-List-Extra.html#v:dropEnd

**Comment by notgiorgi** [comment]
I'm willing to contribute
