### ISSUE TITLE
STArray instances

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-arrays#119]
Typeclass instances for `STArray`?

**Comment by paf31** [comment]
Which ones did you have in mind?

**Comment by matthewleon** [comment]
At a minimum, `Eq`, `Ord`, `Show`. Admittedly many of the others defeat the purpose of using an `STArray`. And of course, you can always `unsafeFreeze` to do typeclassy things. But should that be necessary?

**Comment by natefaubion** [comment]
`STArray`s are inherently referential. I don't think instances like `Eq` or `Ord` are a good idea. I know `Ord` is definitely unsound. If you put an `STArray` in a `Map`, and then mutate the `STArray`, you will have a bad ordering. What does it mean to `map` over an `STArray`? Should it give you a new STArray? This defeats the points of using an STArray.

**Comment by hdgarrood** [comment]
Agreed, you'd need the result in Eff to do these things normally (for a reason). Show could be useful though, although I think its implementation would have to be something like `const "<STArray>"`?

**Comment by matthewleon** [comment]
Thanks for the advice on this. I'll close this one. We could open a separate Issue for `Show`.
