### ISSUE TITLE
deprecate verbose ST function names

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-arrays#129]
`pushSTArray`, `pokeSTArray`, etc. could be exported as `push` and `poke`. Library users could use qualified imports for disambiguation.

**Comment by hdgarrood** [comment]
Big :+1: from me, this has vaguely bothered me for a while. I’d like to wait and see what others think though.

**Comment by garyb** [comment]
No argument from me, I always import this stuff qualified anyway.

**Comment by garyb** [comment]
Resolved in the 0.12 branch
