### ISSUE TITLE
fromFoldable: use foldl

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-arrays#134]
`fromFoldableImpl` currently uses `foldr`. Shouldn't it be possible to write a `foldl`-based implementation? Generally speaking, the `foldl` implementations for core PS data structures seem to be more efficient, if only because they can avoid tricks needed for stack safety.

**Comment by garyb** [comment]
Looks like at least one version of a `foldl` implementation was less efficient: https://github.com/purescript/purescript-arrays/pull/55

**Comment by matthewleon** [comment]
> Looks like at least one version of a foldl implementation was less efficient

From reading the thread, it looks like the decision to opt for `foldr` was not based on efficiency, but on a concern regarding passing an effectful function to `foldl`, expressed here: https://github.com/purescript/purescript-arrays/pull/55#issuecomment-189734558

This leads me to believe that a `foldl`-based alternative would probably live best in a separate lib. I actually wonder if what you'd want would be a `fromTraversable` that just uses `foldl` under the hood, as I would guess that if the `Traversable` laws hold, then you should be able to guarantee the safety of using `foldl` in this way. Curious if anyone else has thought along these lines.
