### ISSUE TITLE
Should we have a specialized version of `find`?

### ISSUE THREAD

**Issue by paulyoung** [purescript/purescript-arrays#143]
I'm thinking this will be better because it won't continue to process the remainder of the array after finding a match.

```purescript
find :: forall a. (a -> Boolean) -> Array a -> Maybe a
find p xs = findIndex p xs >>= index x
```

**Comment by paulyoung** [comment]
@themattchan came up with this, which is even better:

```purescript
find :: forall a. (a -> Boolean) -> Array a -> Maybe a
find f xs = unsafePartial $ unsafeIndex xs <$> findIndex f xs
```

**Comment by kl0tl** [comment]
This was done in https://github.com/purescript/purescript-arrays/pull/189.
