### ISSUE TITLE
intersperse

### ISSUE THREAD

**Issue by jfilip** [purescript/purescript-arrays#15]
Very useful functions for combining arrays of monoids (like strings)

**Comment by hdgarrood** [comment]
I think intersperse should stay in foldable-traversable, but I also think a monomorphic `Array.intercalate :: forall a. a -> Array a -> Array a` would be a good thing to add here. Shall we reopen this?

**Comment by hdgarrood** [comment]
Agh, got them the wrong way around.

**Comment by joneshf** [comment]
Given that we all seem to always get these names wrong, it seems like they could have better names.

In any case, I'm all for a `forall a. a -> Array a -> Array a` in here.

**Comment by garyb** [comment]
There's `joinWith` for `String`, which is similar, but it does somewhat overload the meaning of `join` in the case of arrays. 🤷‍♂️

**Comment by aranchelk** [comment]
AFAIK the words don't have a common origin, but the first time I saw "intercalate" in the Haskell docs it occurred to me: "Ah, it intersperses and then it collates." the mnemonic really stuck. I'd very much appreciate having both functions.

**Comment by JordanMartinez** [comment]
I'm claiming this one. Will be submitting a PR shortly.
