### ISSUE TITLE
add pop, shift, unshift to STArray

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-arrays#151]
Just like the methods of the same names on a JS Array:

- `pop` removes the last item of an array and returns that item
- `shift` removes the first item of an array and returns that item
- `unshift` takes an item and sets it as the first element of the array, shifting everything else along by 1

**Comment by 8084** [comment]
I'm going to implement this. Should I add `unshiftAll` as well, similar to `pushAll`?
