### ISSUE TITLE
Is there a reason we don't have `filterM` function in Data.Array?

### ISSUE THREAD

**Issue by shubham399** [purescript/purescript-arrays#161]

**Comment by shubham399** [comment]
I have written a version, but i would like to know the reason as it be some edge case which i am not thinking.

```
filterM :: forall a m. Monad m => (a -> m Boolean) -> Array a -> m (Array a)
filterM fn array = case uncons array of
  Nothing -> pure []
  Just { head: x, tail: xs } -> do
      b <- fn x
      xs' <- filterM fn xs
      pure if b then x : xs' else xs'
```
because this can do the job.

**Comment by garyb** [comment]
`filterA` is what you're looking for 🙂. `Monad` is a stronger constraint than is required, so it's only `Applicative` in PS.

The `filterM` you described there will be rather inefficient in PS by the way, it wouldn't be so bad if this was `List`, but `uncons` for `Array` is `O(n)`.
