### ISSUE TITLE
Versions of `insertAt` (and friends) that return original array when index is out-of-bounds

### ISSUE THREAD

**Issue by milesfrain** [purescript/purescript-arrays#170]
A common use case is to just keep the original array instead of returning `Nothing` when the index is out-of-bounds, like so:
```hs
updateAt_ :: forall a. Int -> a -> Array a -> Array a
updateAt_ i x xs = fromMaybe xs (updateAt i x xs)
```
Should these wrappers be included in this library? Thoughts on naming?

There's an opportunity to add another version of [`updateAtIndices`](https://pursuit.purescript.org/packages/purescript-arrays/5.3.1/docs/Data.Array#v:updateAtIndices) that returns `Nothing` when any index is out of bounds. Would this be useful? Might need to rename the original for consistency:
``` hs
-- original (name changed)
updateAtIndices_ :: forall t a. Foldable t => t (Tuple Int a) -> Array a -> Array a
-- new (name overwrite)
updateAtIndices :: forall t a. Foldable t => t (Tuple Int a) -> Array a -> Maybe (Array a)
```

`Data.List.Lazy`'s `updateAt` has similar behavior to the existing `updateAtIndices`, and returns the original List when out-of-bounds. I assume there can't be another version with `Maybe`, since that would defeat the benefits of laziness.
```hs
-- original
updateAt :: forall a. Int -> a -> List a -> List a
-- considered
maybeUpdateAt :: forall a. Int -> a -> List a -> Maybe (List a)
```

**Comment by hdgarrood** [comment]
Previously: https://github.com/purescript/purescript-arrays/issues/60

**Comment by milesfrain** [comment]
Should `updateAtIndices` be changed for consistency?

**Comment by natefaubion** [comment]
The issue with`updateAtIndices` is that returning a `Maybe` doesn't give you interesting information, except that some index somewhere failed. It would have to be something like `Maybe (Array Int)`. I didn't even know that function existed :D I think the ship has sailed, personally.

**Comment by hdgarrood** [comment]
Maybe? I don't know. It does feel inconsistent, because the library can't decide whether updating at a nonexistent index should return a `Nothing` or just ignore that update. I don't love the Maybe versions honestly, I feel like in practice these functions always end up being used like `fromMaybe xs $ updateAt _ _ xs`. But changing them at this point would likely be very painful. I feel like we would need to consult the community at this point if we were going to change anything to make it more consistent.

**Comment by hdgarrood** [comment]
I'm also a bit unhappy about the fact that lazy lists are inconsistent (because out-of-bounds updates are ignored there, there's no Maybe). I didn't realise this until your other PR just now.
