### ISSUE TITLE
fromFoldable1 should have Partial in type

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [purescript/purescript-arrays#177]
Shouldn't `fromFoldable1` have partial in its type?
```
fromFoldable1 :: forall f a. Partial => Foldable1 f => f a -> NonEmptyArray a
```
https://github.com/purescript/purescript-arrays/blob/463dcacb99455de5e28ac4a3312bb795f293d2d9/src/Data/Array/NonEmpty.purs#L158-L158

**Comment by JordanMartinez** [comment]
I don't believe so. Why do you think it needs a `Partial` type class?

**Comment by hdgarrood** [comment]
It shouldn’t, no. The difference between Foldable and Foldable1 is that the latter can only be implemented for structures with a minimum of one element, so a Foldable1 constraint is enough to guarantee that we can always construct a NonEmptyArray.

**Comment by BebeSparkelSparkel** [comment]
Thanks for the explanation. My eyes totally glazed over the **1** in `Foldable1`
