### ISSUE TITLE
Move unsafeFreeze and unsafeThaw to Data.Array.ST.Unsafe

### ISSUE THREAD

**Issue by kl0tl** [purescript/purescript-arrays#185]
Data.Array.ST exports unsafeFreeze and unsafeThaw but the foreign object version of unsafeFreeze is exported from Foreign.Object.ST.Unsafe and in https://github.com/purescript/purescript-record/issues/68 I proposed to export record versions of these from Record.ST.Unsafe. Should we extract them to a new Data.Array.ST.Unsafe module for consistency?

**Comment by JordanMartinez** [comment]
I think we should be consistent across all of the ST repos, so I'm for this.

**Comment by hdgarrood** [comment]
Sorry for waiting until there was a PR before stepping in, but I'd actually prefer to change the Foreign.Object ones to be exported from the regular Foreign.Object.ST module - i.e. not bother with separate Unsafe modules. In my view, putting unsafe functions in their own Unsafe module doesn't really achieve very much. The main reason I can think of separating them would be to prevent accidental use of them, but I don't think this actually happens in practice: if a user didn't spot the `unsafe` prefix on the function name, then they almost certainly won't spot the module name difference. Putting unsafe functions into their own module does, however, have the drawback that you have to import more stuff to get things done. In general I think we should aim to have fewer modules.

**Comment by JordanMartinez** [comment]
> The main reason I can think of separating them would be to prevent accidental use of them, but I don't think this actually happens in practice: if a user didn't spot the unsafe prefix on the function name, then they almost certainly won't spot the module name difference.

There have been times where I've imported a function with the same name I wanted but which came from a different module. It can take some time to figure out that the imported module is the issue, not the function itself, when I'm dealing with compiler errors.

I'd prefer to not have an Unsafe module either. If we do that here, then we should do that everywhere with ST modules.

**Comment by kl0tl** [comment]
Having fewer modules sounds like a fair goal to me, let‘s close this then!
