### ISSUE TITLE
Rename empty to new in Data.Array.ST

### ISSUE THREAD

**Issue by kl0tl** [purescript/purescript-arrays#186]
The foreign object equivalent of Data.Array.ST.empty is called new and in https://github.com/purescript/purescript-record/issues/68 I proposed to add Record.ST.new for consistency. Should we also rename Data.Array.ST.empty to new then?

**Comment by JordanMartinez** [comment]
I think we should be consistent across all of the ST repos, so I'm for this.

**Comment by JordanMartinez** [comment]
This was closed by #191.
