### ISSUE TITLE
Restore stability for sorting

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript-arrays#196]
See the following:
- #158 that originally documented the sort stability issue
- #195 which updated the sort functions to no longer depend on the JS backend's `sort` function
- [Harry's comment in #158](https://github.com/purescript/purescript-arrays/pull/158#issuecomment-750488012), stating

> we should still document the stability of our sort, whether it is stable or not. I’m not sure if the new sort algorithm is stable - we should verify this, and if it is, we should document this and add tests for stability (so that we don’t accidentally lose stability later)

**Comment by ptrfrncsmrph** [comment]
I made a simple stability test for `sortWith` that appears to be failing https://github.com/purescript/purescript-arrays/commit/7ad7cfb272a1b9186bfd90fd18cea83c22f9cb19

**Comment by hdgarrood** [comment]
Come to think of it, imo it's quite important for our `sort` to be stable, since the previous implementation was (see https://github.com/purescript/purescript-arrays/pull/158) and people might have been relying on its stability.

**Comment by ptrfrncsmrph** [comment]
Does [this](https://github.com/purescript/purescript-arrays/pull/197/commits/84b3e9143860c8d4bda8d000f8c1ff5030fea902) effectively stabilize the merge sort? (Compare indices if values are equal by comparison)
