### ISSUE TITLE
Enable user to specify which sorting algorithms to use when sorting.

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript-arrays#199]
This does not need to be figured out before the v0.14.0 release

We've updated the default sorting algorithm here to use mergesort. Would it be worthwhile to enable one to use specific algorithms when sorting? For example, [quardsort](https://github.com/scandum/quadsort)?

**Comment by hdgarrood** [comment]
I don't think so, I think in the majority of cases the user probably doesn't really care as long as it's a sensible algorithm (i.e. stable and not quadratic). If people care enough to implement a different sorting algorithm then I think we should encourage them to do that outside of the core libraries; from our perspective, it is sufficient for 99% of use cases to just pick a sensible default sorting algorithm, so I don't think it's worth going that far out of our way to satisfy the remaining 1% (especially if we won't be able to be sure we've even done it adequately).

**Comment by JordanMartinez** [comment]
Well thought-out answer. Sounds good to me!
