### ISSUE TITLE
export slice

### ISSUE THREAD

**Issue by jutaro** [purescript/purescript-arrays#21]
I need slice for matrices (purescript-matrix package). I would like to see this exported, as I don't need to replicate the function then. 
I think it is justified in the interface, as arrays are arrays and not lists.

**Comment by garyb** [comment]
`slice` isn't exported because you can give it nonsensical arguments like `slice(5, 1)`, the preferred approach is `drop` then `take`, although admittedly that has more of a performance penalty.

**Comment by jutaro** [comment]
What do you think about exporting slice with bounds check?

2015-01-06 11:40 GMT+01:00 Gary Burgess <notifications@github.com>:

**Comment by jutaro** [comment]
And as well we have an Unsafe module, maybe it is possible to add slice without bounds check their? For the implementation of vector and matrix the drop and take interface is nonsense.

**Comment by garyb** [comment]
Yeah, making it available via `Unsafe` seems sensible to me.

**Comment by paf31** [comment]
What about `STArray`?
