### ISSUE TITLE
question about Lazy => some

### ISSUE THREAD

**Issue by jamesdbrock** [purescript/purescript-arrays#221]
What is an example of a case where this combinator terminates, and where it would not terminate without the `Lazy` constraint?

If I remove the `Lazy` constraints then it builds and the tests pass.

https://github.com/purescript/purescript-arrays/blob/d20bae2f76db6cf29b7b75e26e82b8a54c32295e/src/Data/Array.purs#L201-L206

**Comment by natefaubion** [comment]
Are there any tests that exercise some/many? Some and many are mutually recursive with strict applicative combinators, which will strictly build an infinite structure.

**Comment by jamesdbrock** [comment]
Oh, there are no tests for `some` and `many`.

https://github.com/purescript/purescript-arrays/blob/1e56c03cf78e875fb4872b2e43b8414b93893060/test/Test/Data/Array.purs#L50-L51

**Comment by jamesdbrock** [comment]
Hm it's a bit tricky to write those tests, I can see why Gary punted on it. You could even say he *deferred* the tests.

I guess the answer to my question is that the combinator always requires `Lazy` to terminate.
