### ISSUE TITLE
`mapWithIndex` should reuse `Data.FunctorWithIndex.mapWithIndexArray`

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript-arrays#232]
This library defines the monomorphic `mapWithIndex` function as [a `zipWith` function on the initial array and an indices-array constructed using the input array's size](https://github.com/purescript/purescript-arrays/blob/master/src/Data/Array.purs#L740-L742). I'd guess it's actually slower than just using `FunctorWithIndex.mapWithindex`. 

The actual monomorphic and dictionary-less `mapWithIndex` FFI is defined in [`foldable-traversable` via `mapWithIndexArray`](https://github.com/purescript/purescript-foldable-traversable/blob/master/src/Data/FunctorWithIndex.purs#L38). Perhaps the `mapWithIndexArray` could be exported in `FunctorWithIndex`, such that we can re-export here under the name `mapWithIndex`?

**Comment by natefaubion** [comment]
I think the FFI implementation needs to move here because foldable-traversable depends on arrays.

**Comment by natefaubion** [comment]
I think that exporting a monomorphic version that's just an alias of the dictionary version would have identical performance characteristics because it would be partially applied.

**Comment by JordanMartinez** [comment]
Works for me.
