### ISSUE TITLE
Differences from Haskell in take/drop

### ISSUE THREAD

**Issue by jacereda** [purescript/purescript-arrays#25]
Haskell:

    Prelude> take (-1) [1,2,3]
    []
    Prelude> drop (-1) [1,2,3]
    [1,2,3]

PureScript:

    > take (-1) [1,2,3]
      [1,2]
    
    > drop (-1) [1,2,3]
      [3]

I haven't seen the differences documented anywhere. If these are intended, a note in https://github.com/purescript/purescript/wiki/Differences-from-Haskell would be nice.

IMHO take/drop should keep haskell semantics and 'slice' should be exported keeping JS semantics.

**Comment by jacereda** [comment]
On a side note, leaving 'slice' as it is would allow implementing 'init' as:

    init :: forall a. [a] -> Maybe [a]
    init [] = Nothing
    init xs = ixs xs
    ixs = Just <<< slice 0 (-1)

I think that would be faster than the current implementation.

**Comment by paf31** [comment]
Well, we could put `slice` in `Data.Array.Unsafe`.

**Comment by sharkdp** [comment]
:+1: for keeping the Haskell semantics.

See corresponding issue/PR for Data.String: https://github.com/purescript/purescript-arrays/issues/25
