### ISSUE TITLE
Should findIndex return Maybe Number instead of failing with -1?

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript-arrays#36]
Let me start by saying that I really like how `head`, `tail` and other functions in this module are safe by default (compared to Haskell). Considering this, it seems strange to me that `findIndex` (and three related functions) have the type
```purescript
findIndex :: forall a. (a -> Boolean) -> [a] -> Number
```
and fail with `-1`. While this is technically not 'unsafe' behavior, the `-1` should not be used as an array index. Right now, I don't see how the `-1` value is useful other than signalling failure. For me, it would feel more natural if the type would simply be
```purescript
findIndex :: forall a. (a -> Boolean) -> [a] -> Maybe Number
```
and failure would be indicated by `Nothing`.

**Comment by paf31** [comment]
:+1: Sounds good to me.

**Comment by garyb** [comment]
We could also change it to use `Int` from `purescript-integers` instead of `Number` perhaps, as we're adding the compiler optimisation for integers now.
