### ISSUE TITLE
(!!) : compilation fails

### ISSUE THREAD

**Issue by hsugawa8651** [purescript/purescript-arrays#38]
The compilation of `(!!)` function fails by the lack of `complement` function used in `isInt` function (l.78).

Rather, I prefer to define `isInt` as follows by calling inline JavaScript function.
```
isInt n = foreign import isInt
 "function isInt(n) { return ( Math.floor(n) === n ); }" :: Number -> Boolean 
```

**Comment by garyb** [comment]
I assume you're using the `psc` from `master` if you're getting this error?

For now, we've not updated the libraries to work with this version yet. If you downgrade to 0.6.9.3 it should be fine.

**Comment by garyb** [comment]
This should be fine now if using the 0.7 compiler release candidate and a `v0.4.0-rc` release of the library.
