### ISSUE TITLE
Arrays is missing `fromFoldable` and `toFoldable`

### ISSUE THREAD

**Issue by chrisdotcode** [purescript/purescript-arrays#53]
cf. [purescript-lists/#53](https://github.com/purescript/purescript-lists/issues/53)

**Comment by chrisdotcode** [comment]
Coincidentally, that's issue #53 there, and this is also issue #53.

I guess it was destined to happen.

**Comment by garyb** [comment]
:smile:

**Comment by sharkdp** [comment]
Adding `toUnfoldable` (I suppose that is what you mean) is not possible at the moment, because that would introduce a cyclic dependency (-unfoldable depends on -arrays).

I guess this could be solved by moving the `Unfoldable Array` instance from -unfoldable to -arrays.

**Comment by garyb** [comment]
We can't move the instance as the `Array` type is defined in `Prim`, not `Data.Array`, so it will be an orphan if it's declared anywhere else.

I guess we'll need to switch to an FFI implementation though, so we can drop the dependency on `-arrays`.
