### ISSUE TITLE
union, unionBy are not symmetrical in their arguments

### ISSUE THREAD

**Issue by sharkdp** [purescript/purescript-arrays#56]
This seems weird:
```purs
union [0, 0] [1, 1] == [0, 0, 1]
```
I would have expected the result to be `[0, 1]`, but at least it should be symmetrical in both arguments. I would consider several possible fixes:

1. Remove all duplicates (i.e. `union a b == nub (a <> b)`)
2. Keep the duplicates within both of the arguments (i.e. `union [0, 0] [1, 1] == [0, 0, 1, 1]`).
3. Remove `union` and `unionBy` from `Data.Array` (given that `Set` is the better data structure for something like this)
4. Document the behavior if it is intended

I would vote for 1 or 3.

**Comment by garyb** [comment]
It definitely seems weird, although we seem to have inherited it from Haskell where it is documented as preserving duplicates in the first list. I'd vote for 3 or 4.

**Comment by sharkdp** [comment]
> although we seem to have inherited it from Haskell where it is documented as preserving duplicates in the first list

Ah, good point. The same thing applies for `intersect`.

**Comment by garyb** [comment]
I can see how this behaviour makes sense for something like `(\\)` but I'm not so clear why you'd want it for the "set-like" functions - maybe there is a good reason though? Maybe we should indeed ditch all of the pseudo-set functions if we can't come up with a good reason for this unusual behaviour.
