### ISSUE TITLE
Use an index instead of uncons to make array functions more efficient.

### ISSUE THREAD

**Issue by jutaro** [purescript/purescript-arrays#71]
The implementation of many array functions, like filterM, span, groupBy, ... uses uncons for implementation. It would be more efficient to use an index and has no known disadvantages (other then maybe some subjective aesthetic property).

If we can agree on this I can contribute code, but I don't want to work on this if it is not wanted.

**Comment by paf31** [comment]
Let's list out the functions which have possible issues, since I think each could have a slightly different fix.

`filterM` - I'm not sure how you could make this more efficient for a general `Monad`.

`span` and `groupBy` could potentially make use of `STArray`. Something like `discrimination` is probably worth investigating for sorting and grouping too.

**Comment by hdgarrood** [comment]
I think converting to a list before doing `filterM` and then converting back to an Array at the end would be better than the current implementation; right now it's at least O(n^2) I think.

**Comment by hdgarrood** [comment]
Mostly a note to myself: now, it's just `groupBy`, `nubBy`, `unzip`, and `foldM` that use `uncons` (and perhaps shouldn't).

**Comment by hdgarrood** [comment]
`groupBy` is now done, so I'll make a checklist for the remaining ones:

* [ ] `nubBy`
* [ ] `unzip`
* [ ] `foldM`

**Comment by hdgarrood** [comment]
That sounds good to me, provided that the `Foldable` has better performance than the current `foldM` — which is almost certainly true but probably still worth checking, at least for one or two monads.

**Comment by hdgarrood** [comment]
`nubByEq` was the last problematic one, so I'm going to close this, but of course please continue to open issues if you find places where performance could be improved.
