### ISSUE TITLE
head not O(1)

### ISSUE THREAD

**Issue by jacereda** [purescript/purescript-arrays#76]
Looks like `head` isn't O(1), at least on node v4.4.7.

I measured with purescript-benchotron as follows:

```
benchHead :: Benchmark
benchHead = mkBenchmark
  { slug: "head"
  , title: "Head of a structure"
  , sizes: (1 .. 8) <#> (_ * 150)
  , sizeInterpretation: "Number of elements in the structure"
  , inputsPerSize: 1
  , gen: randomArray
  , functions: [ benchFn "Array" A.head
               , benchFn "Array'" (_ `A.index` 0)
               ]
  }
```

**Comment by hdgarrood** [comment]
Ah, right, yeah, because it uses `uncons`, which does `xs.slice(1)`. In fact looking through the code in `src/Data/Array.purs` I suspect most of the other uses of `uncons` or `uncons'` could probably be reworked for better performance.
